title: IJ2gDocs
description: >-
  Mirror a file opened in IntelliJ IDEA™ to Google Docs™
baseurl: "/IJ2gDocs"
url: ""
github_username:  danthe1st
markdown: kramdown
remote_theme: pages-themes/architect@v0.2.0

include:
  - LICENSE.md
  - privacy.md
  - README.md
